name: Node.js CI

on: push

jobs:

  install-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      
    - name: Node install
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: NPM build & zip
      run: |
        npm ci
        npm run build
        zip -r dist.zip ./dist
        mkdir -p path/to/artifact

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: dist.zip

  deploy:
    runs-on: ubuntu-latest
    needs: [install-build]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: artifact

    - name: Unzip artifacts
      run: |
        unzip dist.zip -d ./

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: rsync -avz -R dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/admin/web/evdesign.ru/public_html/demos/website-barba-webgl